version: '2'
services:
    jhsmarttle-app:
        image: jhsmarttle
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhsmarttle-mysql:3306/jhsmarttle?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhsmarttle-mysql:
        extends:
            file: mysql.yml
            service: jhsmarttle-mysql
